In [1]:
from kaldo.forceconstants import ForceConstants
import os

2026-05-11 15:33:13.985530: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-05-11 15:33:14.068318: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-05-11 15:33:16.182875: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.


### Silicon (216 Atom Supercell, 2 Atom Primitive Cell)

In [ ]:
tdep_dir = os.path.abspath("./kaldo/tests/si-tdep2")
# 50 seconds on Ethans Desktop :(
fc = ForceConstants.from_folder(
        folder=str(tdep_dir), format="tdep", supercell = (3,3,3), include_fourth=True,
    )

(108, 1, 1)


In [ ]:
# 1.2 seconds on Ethans Desktop
fc2_sc = fc.irred_to_full(order = 2)
print(fc2_sc.shape)
print(fc2_sc[0,0,:,0,0,:].reshape(3,3))

(108, 2, 3, 108, 2, 3)
[[16.9283923  0.         0.       ]
 [ 0.        16.9283923  0.       ]
 [ 0.         0.        16.9283923]]


In [ ]:
# 3.9 seconds on Ethans Desktop
fc3_sc = fc.irred_to_full(order = 3)
print(fc3_sc.shape)
print(fc3_sc[0,0,:,0,0,:,0,0,:].reshape(3,3,3))

(108, 2, 3, 108, 2, 3, 108, 2, 3)
[[[ 0.          0.          0.        ]
  [ 0.          0.         27.54734769]
  [ 0.         27.54734769  0.        ]]

 [[ 0.          0.         27.54734769]
  [ 0.          0.          0.        ]
  [27.54734769  0.          0.        ]]

 [[ 0.         27.54734769  0.        ]
  [27.54734769  0.          0.        ]
  [ 0.          0.          0.        ]]]


In [5]:
fc4_sc = fc.irred_to_full(order = 4)
print(fc4_sc.shape)
print(fc4_sc[0,0,:,0,0,:,0,0,:,0,0,:].reshape(3,3,3,3))

ValueError: order must be 2 or 3, got 4.

### Argon (256 Atom Supercell, 1 Atom Primitive Cell)

In [3]:
tdep_dir = os.path.abspath("./kaldo/tests/lj-tdep")
fc = ForceConstants.from_folder(
        folder=str(tdep_dir), format="tdep", supercell = (4,4,4), include_fourth=False,
    )

(256, 1, 1)
