In [15]:
from kaldo.interfaces.tdep_io import (
    remap_force_constants, 
    parse_tdep_forceconstant,
    parse_tdep_third_forceconstant
)
from kaldo.forceconstants import ForceConstants

import ase
import os
import numpy as np

In [12]:
basepath = os.path.abspath("./SW")
fc_path = os.path.join(basepath, "100K_3UC", "infile.forceconstant")
fc3_path = os.path.join(basepath, "100K_3UC", "infile.forceconstant_thirdorder")
fc4_path = os.path.join(basepath, "100K_3UC", "infile.forceconstant_fourthorder")
uc_path = os.path.join(basepath, "infile.ucposcar")
sc_path = os.path.join(basepath, "infile.ssposcar")

uc = ase.io.read(uc_path, format = "vasp")
sc = ase.io.read(sc_path, format = "vasp")
M = np.linalg.solve(np.asarray(uc.cell), np.asarray(sc.cell))
print(uc)
print(sc)
print(M)

Atoms(symbols='Si2', pbc=True, cell=[[2.715, 2.715, 0.0], [0.0, 2.715, 2.715], [2.715, 0.0, 2.715]])
Atoms(symbols='Si216', pbc=True, cell=[16.29, 16.29, 16.29])
[[ 3. -3.  3.]
 [ 3.  3. -3.]
 [-3.  3.  3.]]


In [3]:
ifc_2d = parse_tdep_forceconstant(fc_path, uc, sc)
ifc_primitive = parse_tdep_forceconstant(fc_path, uc, sc, two_dim=False)

print(ifc_2d.shape)
print(ifc_primitive.shape)

(648, 648)
(216, 216, 3, 3)


In [5]:
from kaldo.cumulant.common import read_tdep_ifc3, read_tdep_ifc4

n_uc = 2
ifc3 = read_tdep_ifc3(fc3_path, n_uc)
ifc4 = read_tdep_ifc4(fc4_path, n_uc)

In [ ]:
# tdep_dir = os.path.abspath(os.path.join(basepath, "100K_3UC"))
# fc = ForceConstants.from_folder(
#         folder=str(tdep_dir), format="tdep", include_fourth=True,
#     )

In [19]:
tdep_dir = os.path.abspath("../si-tdep")
fc = ForceConstants.from_folder(
        folder=str(tdep_dir), format="tdep", supercell = (5,5,5), include_fourth=False,
    )

125


In [21]:
fc.atoms.get_masses()

array([28.085, 28.085])

In [22]:
fc.second.replicated_atoms

Atoms(symbols='Si250', pbc=True, cell=[[0.0, 13.591103167277915, 13.591103167277915], [13.591103167277915, 0.0, 13.591103167277915], [13.591103167277915, 13.591103167277915, 0.0]])